# -*- coding: utf-8 -*-
"""data_cleaning_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qlxd3cWvnjXIlKwJLHPXsDZZM1a47qI6
"""

import numpy as np
import pandas as pd

# Load dataset
df = pd.read_csv("sample_data.csv")

print("Original Dataset:\n", df)

# Check missing values
print("\nMissing Values:\n", df.isnull().sum())

# Remove rows with missing values
cleaned_df = df.dropna()

print("\nCleaned Dataset:\n", cleaned_df)

# NumPy operations
temperatures = cleaned_df["temperature"].values
avg_temp = np.mean(temperatures)

print("\nAverage Temperature:", avg_temp)

# Group by city and calculate average sales
avg_sales_by_city = cleaned_df.groupby("city")["sales"].mean()

print("\nAverage Sales by City:\n", avg_sales_by_city)