# -*- coding: utf-8 -*-
"""visualization_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RyPc4mNgC6-q9EniiVgKyn6lXNVZsgN
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("sample_data.csv")

# Create plots folder if it doesn't exist
import os
os.makedirs("plots", exist_ok=True)

# 1. Histogram - Temperature Distribution
plt.figure()
plt.hist(df["temperature"].dropna())
plt.title("Temperature Distribution")
plt.xlabel("Temperature")
plt.ylabel("Frequency")
plt.savefig("plots/histogram.png")
plt.close()

# 2. Scatter Plot - Temperature vs Sales
plt.figure()
plt.scatter(df["temperature"], df["sales"])
plt.title("Temperature vs Sales")
plt.xlabel("Temperature")
plt.ylabel("Sales")
plt.savefig("plots/scatter_plot.png")
plt.close()

# 3. Heatmap - Correlation Matrix
corr_matrix = df.select_dtypes(include="number").corr()

plt.figure()
sns.heatmap(corr_matrix, annot=True)
plt.title("Correlation Heatmap")
plt.savefig("plots/heatmap.png")
plt.close()

print("Plots created successfully and saved in the 'plots' folder.")