# -*- coding: utf-8 -*-
"""average_temperature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJqloVEl5g823VftOkrJ6-P_2lZqcw0g
"""

# List of temperature readings (in Celsius)
temperatures = [28.5, 30.2, 29.8, 31.0, 27.6, 28.9]

# Check if the list is not empty
if len(temperatures) > 0:
    average_temperature = sum(temperatures) / len(temperatures)
    print(f"Average Temperature: {average_temperature:.2f} °C")
else:
    print("No temperature data available.")

temps = [30, 32, 31, 29, 33, 34, 30]
avg_temp = sum(temps) / len(temps)
print("Average Temperature:", avg_temp)

# Average Temperature Calculator

temperatures = []

days = int(input("Enter number of days: "))

for i in range(days):
    temp = float(input(f"Enter temperature for day {i+1}: "))
    temperatures.append(temp)

average_temp = sum(temperatures) / len(temperatures)
max_temp = max(temperatures)
min_temp = min(temperatures)

print("\nTemperature Summary")
print("Average Temperature:", average_temp)
print("Maximum Temperature:", max_temp)
print("Minimum Temperature:", min_temp)