# -*- coding: utf-8 -*-
"""temperature_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQJBpVEVFquJozrFD1QCe_L4lSADxsea
"""

# Temperature Converter
# Converts Celsius to Fahrenheit and Fahrenheit to Celsius

print("Temperature Converter")
print("1. Celsius to Fahrenheit")
print("2. Fahrenheit to Celsius")

choice = int(input("Enter your choice (1 or 2): "))

if choice == 1:
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}°C = {fahrenheit}°F")

elif choice == 2:
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}°F = {celsius}°C")

else:
    print("Invalid choice")