# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQTpZP3x1alM7sS2eiXPIlHe0AUxfmeN
"""

# Data Cleaning Script

data = [10, 20, 20, 30, 40, 50, 50, 60]

print("Original Data:", data)

# Remove duplicates
cleaned_data = list(set(data))

# Filter values greater than 30
filtered_data = [x for x in cleaned_data if x > 30]

print("Cleaned Data (No Duplicates):", cleaned_data)
print("Filtered Data (Values > 30):", filtered_data)