# -*- coding: utf-8 -*-
"""functions_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbZF8qYt_k_JL65TNjfEDiabdMslli74
"""

# Functions Practice

# Function to calculate sum of squares
def sum_of_squares(numbers):
    return sum([n ** 2 for n in numbers])

numbers = [1, 2, 3, 4, 5]
print("Sum of Squares:", sum_of_squares(numbers))

# Lambda function
square = lambda x: x ** 2
print("Square of 6:", square(6))

# Filter even numbers
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even Numbers:", even_numbers)